### PR TITLE
Return `NULL` for several cases when related objects are not found.

### LINKED ISSUE #90: CompositeResourceClaim spec.composition can throw error when not present
### What happened?

When a `CompositeResourceClaim`s `spec.compositionRef.name` is not set to a valid composition name queries that reference `spec.compoisition` fail. One specific case is when the `name` is `""` which it is when a composition has not yet been selected. Similarly the `spec.resourceRef` can have values that point at an object that does not or no longer exists and also causes `spec.resource` queries to fail. Both of these cases seem to be non-exceptional. They may be a degenerate or error state but not exceptional. The current behavior fails the whole query which is an exceptional case. The query should not fail but rather return either an `NULL` (and make these fields nullable) or return a `union` and define an error case that explains why they are not present. Also, I suspect that. `spec.compositionRevisionRef` is another instance of this issue.

### How can we reproduce it?

Construct a `CompositeResourceClaim` that has a `compositionRef` and/or a `resourceRef` that does not point to something valid.

### What environment did it happen in?

dev

### PR DESCRIPTION
**Pull request by thephred**
### Description of your changes

Return `NULL` for several cases when related objects are not found.

Resolves #90

I have:

- [x] Read and followed Upbound's [contribution process](https://git.io/fj2m9).
- [x] Run `make reviewable` to ensure this PR is ready for review.
- [ ] Added `backport release-x.y` labels to auto-backport this PR, as appropriate.

### How has this code been tested

Just ran `make` and `make reviewable`.

### CODE REVIEW

**Comment by thephred** [comment]
@negz this is one possible solution to the linked issue (#90). It simply returns `NULL` (GraphQL response) when the related object was not found instead of failing the whole GraphQL query. Alternative might be to return an `union` that is either the success object or an error type.

**Review by negz — APPROVED** [review]
This LGTM.

It does make me wonder though - should we have (e.g.) a plain old `compositionRef` field next to the `composition` resolver? My thinking is that while `NULL` feels appropriate for both the case in which the claim doesn't reference a composition and the case where the claim references a composition that doesn't exist, returning `NULL` in both cases means we can't distinguish between them.

**Comment by thephred** [comment]
@negz I was thinking the same thing. I think I will just go ahead and make that change here.

File: internal/graph/resolvers/composite_test.go [hunk 1]
```diff
@@ -47,6 +47,16 @@ var (
...
 
+func AssertNoErrors(t *testing.T, err error, errs gqlerror.List) {
+	if diff := cmp.Diff(nil, err, test.EquateErrors()); diff != "" {
+		t.Errorf("s.CompositionRef(...): -want error, +got error:\n%s\n", diff)
+	}
+
+	if diff := cmp.Diff(gqlerror.List{}, errs, test.EquateErrors()); diff != "" {
+		t.Errorf("s.CompositionRef(...): -want GraphQL errors, +got GraphQL errors:\n%s\n", diff)
+	}
+}
```
Comment (negz) [inline internal/graph/resolvers/composite_test.go:58]: This seems a _little_ close to something Go recommends avoiding - https://github.com/golang/go/wiki/TestComments#assert-libraries. That said, it's just a little helper function (not a full library) so I'm not too worried. It may just be the "assert" terminology that caught my attention.

File: schema/composite.gql [hunk 2]
```diff
@@ -129,10 +140,15 @@ resource claim.
...
   """
-  The composition this composite resource uses to compose resources.
+  The composition this composite resource claim uses to compose resources.
   """
   composition: Composition @goField(forceResolver: true)
 
+  """
+  The compositionRef this composite resource claim uses to compose resources.
+  """
+  compositionRef: String
```
Comment (negz) [inline schema/composite.gql:150]: Should this be an ObjectReference? That would more closely match the underlying "XRM" API.

File: schema/composite.gql [hunk 3]
```diff
@@ -52,6 +57,9 @@ type CompositeResourceSpec {
   """
   claim: CompositeResourceClaim @goField(forceResolver: true)
 
+  "The `ObjectReference` for the composite resource claim that claims this composite resource"
+  claimReference: ObjectReference
```
Comment (negz) [inline schema/composite.gql:61]: I would suggest `claimRef`, as opposed to the full "Reference". I believe that matches the underlying KRM/XRM patterns.

File: schema/common.gql [hunk 4]
```diff
@@ -469,6 +469,44 @@ type ConfigMap implements Node & KubernetesResource {
...
+  """
+  If referring to a piece of an object instead of an entire object, this string
+  should contain a valid JSON/Go field access statement, such as desiredState.manifest.containers[2].
+  For example, if the object reference is to a container within a pod, this would take on a value like:
+  "spec.containers{name}" (where "name" refers to the name of the container that triggered
+  he event) or if no container name is specified "spec.containers[2]" (container with
+  index 2 in this pod). This syntax is chosen only to have some well-defined way of
+  referencing a part of an object.
+  """
+  fieldPath: String
```
Comment (negz) [inline schema/common.gql:498]: I think we should leave these out. Some context in https://github.com/crossplane/crossplane-runtime/issues/49.

File: internal/graph/resolvers/composite_test.go [hunk 5]
```diff
@@ -438,6 +473,33 @@ func TestCompositeResourceSpecClaim(t *testing.T) {
...
+	ctx = graphql.WithResponseContext(context.Background(), graphql.DefaultErrorPresenter, graphql.DefaultRecover)
+	got, err = s.ClaimReference(ctx, &model.CompositeResourceSpec{ClaimReference: nil})
+	errs = graphql.GetErrors(ctx)
+
+	AssertNoErrors(t, err, errs)
+
+	want = nil
+	if diff := cmp.Diff(want, got, test.EquateErrors()); diff != "" {
+		t.Errorf("s.ClaimReference(...): -want, +got:\n%s\n", diff)
+	}
```
Comment (negz) [inline internal/graph/resolvers/composite_test.go:500]: I notice these tests aren't following the table driven conventions of the existing tests - what's the reason for that?

File: schema/composite.gql [hunk 6]
```diff
@@ -61,6 +69,9 @@ type CompositeResourceSpec {
   The resources of which this composite resource is composed.
   """
   resources: KubernetesResourceConnection @goField(forceResolver: true)
+
+  "Reference to the secret this composite resource writes its connection details to"
+  writesConnectionSecretToReference: SecretReference
```
Comment (negz) [inline schema/composite.gql:74]: In the underlying API this is "writeConnection..." not "writesConnection...".

File: internal/graph/resolvers/composite_test.go (hunk 1 above)
Comment (thephred) [reply internal/graph/resolvers/composite_test.go:58]: It was meant as a helper to keep things more DRY. Would something like this be ok or would you suggest just inlining this code in the 12 places it is used?

```go
func checkErrors(t *testing.T, prefix string, err error, errs gqlerror.List) {
	if diff := cmp.Diff(nil, err, test.EquateErrors()); diff != "" {
		t.Errorf("%s: -want error, +got error:\n%s\n", prefix, diff)
	}

	if diff := cmp.Diff(gqlerror.List{}, errs, test.EquateErrors()); diff != "" {
		t.Errorf("%s: -want GraphQL errors, +got GraphQL errors:\n%s\n", prefix, diff)
	}
}
```

File: schema/composite.gql (hunk 2 above)
Comment (thephred) [reply schema/composite.gql:150]: The existing code consuming this only pays attention to the `Name` part of the `ObjectReference`:
https://github.com/upbound/xgql/blob/e0ce8daa9a555b74d82f37c4373bcc1f66d752cf/internal/graph/resolvers/composite.go#L108-L131

I think this means that if you use anything other than the name it won't work. Should we fix that or assume that the ref is always just to a name?

File: internal/graph/resolvers/composite_test.go (hunk 5 above)
Comment (thephred) [reply internal/graph/resolvers/composite_test.go:500]: There were only two cases and I felt the overhead for making it a table was more costly than just repeating. Is it better to just stay consistent you think?

**Review by jmaduroUpbound — APPROVED** [review]
LGTM 🐬

File: internal/graph/resolvers/composite_test.go (hunk 1 above)
Comment (negz) [reply internal/graph/resolvers/composite_test.go]: I personally typically just inline boilerplate code like this, but I can also see why a helper makes sense - no strong feelings. You will probably want to use https://pkg.go.dev/testing#T.Helper to mark the function as such.

File: internal/graph/resolvers/composite_test.go (hunk 5 above)
Comment (negz) [reply internal/graph/resolvers/composite_test.go:500]: I would prefer to stay consistent - especially if it's possible we might add other cases in future.

File: schema/common.gql [hunk 7]
```diff
@@ -469,6 +469,33 @@ type ConfigMap implements Node & KubernetesResource {
...
+  namespace: String
+
+  "Name of the referent."
+  name: String
+
+  "UID of the referent."
+  uid: String
+
+  "API version of the referent."
+  resourceVersion: String
```
Comment (negz) [inline schema/common.gql:487]: I should have been more specific in my last comment - I think we should omit `uid` and `resourceVersion` as well as `fieldPath`.

File: schema/composite.gql (hunk 2 above)
Comment (negz) [reply schema/composite.gql:150]: Yeah, we only need the name here. What I'm thinking though is that we should have the GraphQL schema here "mirror" the XRM API as closely as possible by "nesting" an object with only a single `name` field. So something like:

```graphql
type LocalObjectReference {
  name: String!
}

type CompositeResourceClaimSpec {
  compositionRef: LocalObjectReference
}
```

This is primarily a KRM API conventions thing - it's expected that when you see a field named `<t>Ref` its value will be a subset of the ObjectReference type rather than a string.

File: internal/graph/resolvers/composite_test.go (hunk 1 above)
Comment (thephred) [reply internal/graph/resolvers/composite_test.go]: I'll go ahead and inline.

File: schema/composite.gql (hunk 2 above)
Comment (thephred) [reply schema/composite.gql:150]: Makes sense.

File: schema/common.gql (hunk 7 above)
Comment (thephred) [reply schema/common.gql:487]: On it.

**Review by negz — APPROVED** [review]
Thanks @thephred - this looks great.
